name: Docker Image CI

on:
  release:
    types: [created] # published,created
#  pull_request:
#    branches: [main]

jobs:
      build:
        runs-on: ubuntu-latest
        
        steps:
          - uses: actions/checkout@v2

          - run: re_ver=echo ${{ github.ref }} | cut -d "/" -f 3 | cut -d "v" -f 2

          - name: Build the Docker image
            run: docker build . --file Dockerfile --tag zabbix-server:${{ re_ver }}
       
          
          - name: push to aliyum
            run: |
              docker login --username=${{ secrets.USERNAME }} registry.cn-hangzhou.aliyuncs.com --password=${{ secrets.PASSWORD }}
              docker tag zabbix-server:${{ re_ver }} registry.cn-hangzhou.aliyuncs.com/vcun/zabbix-server:${{ re_ver }}
              docker push registry.cn-hangzhou.aliyuncs.com/vcun/zabbix-server:${{ re_ver }}


