name: Docker Image CI


on:
  push:
    branches: [main]

  release:
    types: [created] # published,created
#  pull_request:
#    branches: [main]

jobs:
      build:
        runs-on: ubuntu-latest

        env:
          var_ltag: ${{ github.ref }}
        
        steps:


          - uses: actions/checkout@v2

          - run: |
             set var_tag=$(echo ${var_ltag} | cut -d "/" -f 3 | cut -d "v" -f 2)
          
          - run: echo ${var_tag}

          - name: Build the Docker image
            run: docker build . --file Dockerfile --tag zabbix-server:${var_tag}
       
          
          - name: push to aliyum
            run: |
              docker login --username=${secrets.USERNAME} registry.cn-hangzhou.aliyuncs.com --password=${secrets.PASSWORD}
              docker tag zabbix-server:${var_tag} registry.cn-hangzhou.aliyuncs.com/vcun/zabbix-server:${var_tag}
              docker push registry.cn-hangzhou.aliyuncs.com/vcun/zabbix-server:${var_tag}


